keys:
  - &yk_pgp 5962486144B0FAE0B535FC9BFF404ABD083C84EC
  - &tower age19dy6xgjsm2fvkyvqvstv83dzjp7nwzd093cgd6cm3tzanh35sq7qr35zh9
  - &pylon age1lgkch86vqgwszsnsvl8lcdmvyfcrked50wrsuwj3adza8nxh7geqhtyr5q
  - &samira age1g2xaldhxyt4cmy2lwv24urdyqkw9xzq528fc7amg2hrjz2e0xdcqw66z7a
  - &soraya age1zwsj98d9rhf30trxng3vy739v5vvs6y5kgkp24jlelg26yluqy8sqpu2u6
  - &sakina age1cdc2cpsxul9lqr5pesxdc42xytsn5kwwmpekchgwwuh97e4drykqwzeva0
  - &biggie age1f8lwjjr8f962za0xh2se3j6axjwhjc958sp72gnssjl2z5wdeeuq75smhg

creation_rules:
  - path_regex: general/secrets.enc.yaml$
    # Make sure to only create a single list to go around shamir_threshold
    key_groups:
    - pgp:
        - *yk_pgp
      age:
        - *tower

  - path_regex: pylon/secrets.enc.yaml$
    key_groups:
    - pgp:
        - *yk_pgp
      age:
        - *pylon
        - *tower

  - path_regex: samira/secrets.enc.yaml$
    key_groups:
    - pgp:
        - *yk_pgp
      age:
        - *samira
        - *tower

  - path_regex: soraya/secrets.enc.yaml$
    key_groups:
    - pgp:
        - *yk_pgp
      age:
        - *soraya
        - *tower

  - path_regex: sakina/secrets.enc.yaml$
    key_groups:
    - pgp:
        - *yk_pgp
      age:
        - *sakina
        - *tower

  - path_regex: biggie/secrets.enc.yaml$
    key_groups:
    - pgp:
        - *yk_pgp
      age:
        - *biggie
        - *tower

  - path_regex: k3s/secrets.enc.yaml$
    key_groups:
    - pgp:
        - *yk_pgp
      age:
        - *tower
        - *samira
        - *soraya
        - *sakina
