[user]
name = "Aos Dabbagh"
email = "25783780+aos@users.noreply.github.com"

[aliases]
d = ["diff"]
l = ["log"]

[ui]
pager = "delta"
default-command = ["log", "-T", "builtin_log_oneline"]

[ui.diff]
format = "git"
